# LFishing v1.2
# karpen-dev - https://github.com/karpen-dev/

# Chances
chances:
  default: 10
  normal: 5
  epic: 3
  mifik: 1
  legend: 0.1

# Messages
msg:
  default: "Вы поймали стандартную коробку!"
  normal: "Вы поймали необычную коробку!"
  epic: "Вы поймали эпическую коробку!"
  mifik: "Вы поймали мифическую коробку!"
  legend: "Вы поймали легендарную коробку!"

# Chat msg
# <playerName> + msg
chat:
  epic: " выловил эпическую коробку!"
  mifik: " выловил мифическую коробку!"
  legend: " выловил легендарную коробку!"

reload:
  args: "Используйте /lfishing reload"
  done: "Плагин перезагружен"

# Box names
names:
  default: "Стандартная коробка"
  normal: "Необычная коробка"
  epic: "Эпическая коробка"
  mifik: "Мифическая коробка"
  legend: "Легендарная коробка"