# LFishing v1.1
# karpen-dev - https://github.com/karpen-dev/

# Chances
chances:
  default: 20
  normal: 10
  epic: 5

# Messages
msg:
  default: "Вы поймали стандартную коробку!"
  normal: "Вы поймали необычную коробку!"
  epic: "Вы поймали эпическую коробку!"

# Box names
names:
  default: "Стандартная коробка"
  normal: "Необычная коробка"
  epic: "Эпическая коробка"