# LFishing v1.5
# karpen-dev - https://github.com/karpen-dev/

# AMPERSAND COLOROS DOESN'T WORK NOW
# CAN BE FIXED SOON...

# Chances
chances:
  default: 10
  normal: 5
  epic: 3
  mifik: 1
  legend: 0.1

# Luck chances
luck:

  # Enable this function
  enabled: true

  default: 12
  normal: 8
  epic: 5
  mifik: 2
  legend: 0.8

# Chatty api
chatty:
  using: true

  # Chat for chat msg
  chat: "global"

# Skins
# Use https://textures.minecraft.net/texture/ only!
skin:
  default: "https://textures.minecraft.net/texture/2cf5b1cfed1c27dd4c3bef6b9844994739851e46b3fc7fda1cbc25b80ab3b"
  normal: "https://textures.minecraft.net/texture/f7145c0ee1cd493664fb1b26622db0492a1969a659931e7a3362d9071fbd4cf8"
  epic: "https://textures.minecraft.net/texture/a1b96fc7d915b57f683493106704353d8837772dff51b20bf3bda09f2fa8b3ba"
  mifik: "https://textures.minecraft.net/texture/2ff4242b1a17cf9ce781a1e33415bb19341f996ec1388ec126ee824af9e72a8d"
  legend: "https://textures.minecraft.net/texture/cdf81449131dcdd3578899fcd9592e13f5cca57ae7481fd6710bb6ca85d65c9"

# Messages
msg:

  # Drop box messages
  default: "Вы поймали стандартную коробку!"
  normal: "Вы поймали необычную коробку!"

  # Top massages
  top: "Топ игроков по количеству открытых коробок: "
  topIsEmpty: "Топ пуст >_<"

  # Errors
  # /getbox cmd
  using: "Используй /getbox <default | normal | epic | mifik | legend>"
  console: "Эту команду может использовать только игрок"

# Chat msg
# %name% - playername - NOW IT'S NOT WORKING
# THIS CAN BE FIXED SOON...
chat:

  # Drop box messages
  epic: "%name% выловил эпическую коробку!"
  mifik: "%name% выловил мифическую коробку!"
  legend: "%name% выловил легендарную коробку!"

reload:
  args: "Используйте /lfishing reload"
  done: "Плагин перезагружен"

# Box names
names:
  default: "Стандартная коробка"
  normal: "Необычная коробка"
  epic: "Эпическая коробка"
  mifik: "Мифическая коробка"
  legend: "Легендарная коробка"