name: LFishing
version: '1.2'
main: com.karpen.lFishing.LFishing
api-version: '1.21'
commands:
  lfishing:
    usage: <command> <args>
    description: Перезагружает плагин
    permission: karpen.lfishing
    permission-message: You don't have permission