name: LFishing
version: '1.4'
main: com.karpen.lFishing.LFishing
api-version: '1.21'
softdepend: [ Chatty ]
commands:
  lfishing:
    usage: /lfishing reload
    description: Перезагружает плагин
    permission: karpen.lfishing
    permission-message: You don't have permission
  getbox:
    usage: /getbox <default | normal | epic>
    description: Выдает коробку
    permission: karpen.lfishing.getbox
    permission-message: You don't have permission
  topbox:
    usage: /topbox
    description: Показывает топ игроков